version: "3.9"
services:
  backend:
    build: .
    container_name: inventory_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./anbar_project:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
