version: "3.9"
services:
  backend:
    build: .
    container_name: backend
    command: gunicorn anbar_project.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./anbar_project:/app
    expose:
      - "8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - backend