# Generated by Django 4.2.7 on 2023-11-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='picture',
            new_name='image',
        ),
    ]
