# Generated by Django 4.2.7 on 2023-11-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_remove_item_image_itemimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ItemImage",
        ),
    ]
