name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker-Compose
      run: docker-compose -f docker-compose-stage.yml up -d
    - name: show container_id
      run: echo $(docker ps | grep "backend" | awk '{print $1}')
#    - name: Makemigrations
#      run: docker-compose exec $(docker ps | grep "backend" | awk '{print $1}') sh -c "python manage.py makemigrations"
#    - name: Migrate
#      run: docker-compose exec $(docker ps | grep "backend" | awk '{print $1}') sh -c "python manage.py migrate"

