name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:

    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker-Compose
      run: docker-compose -f docker-compose-stage.yml up -d
    - name: Run tests
      run: |
        docker ps
        docker exec $(docker ps | grep 'backend' | awk '{print $1}') sh -c "flake8 ."
        # Add more test commands here
        # Return a non-zero exit code if tests fail
        exit 1
      continue-on-error: true

  Deploy:
    if: ${{ always() && needs.Test.result == 'success' }}
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Connect and execute commands
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Running in $(pwd) with user $USER"
            ls
            cd inventory
            docker-compose -f docker-compose-stage.yml stop
            git pull
            git log --oneline
            docker-compose -f docker-compose-stage.yml restart
